server.port= 8083
spring.application.name=auth-service

#jwt
jwt.secret= ${JWT_SECRET}
jwt.exp.time=${JWT_EXP_TIME}
jwt.issuer=${JWT_ISSUER}

#redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.timeout=5000ms
spring.data.redis.lettuce.shutdown-timeout=100ms
otp.ttl=5

#eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE}

#text.lk
otp.endpoint=${OTP_ENDPOINT}
otp.auth-token=${OTP_AUTH_TOKEN}
otp.message-template=${OTP_MESSAGE_TEMPLATE}
otp.sender-id=${OTP_SENDER_ID}


