services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  api-gateway:
    image: joelgallan/api-gateway:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8085:8081"