networks:
  app-network:
    driver: bridge



services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
      - 'RABBITMQ_PLUGINS_ENABLE=rabbitmq_stomp,rabbitmq_web_stomp'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
      - '15674:15674'
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: # <<< THIS MAKES SURE IT JOINS THE NETWORK
      - app-network


  #### MQTT BROKER ####
  emqx-service:
    image: emqx/emqx:latest
    container_name: emqx-service
    restart: always
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
    environment:
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "admin123"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:18083/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: # <<< THIS MAKES SURE IT JOINS THE NETWORK
      - app-network


  #### databases ####

  user_service_db:
    image: postgres:15-alpine
    container_name: user_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pg-user-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d users" ]
      interval: 5s
      timeout: 5s
      retries: 5

  chat_service_db:
    image: postgres:15-alpine
    container_name: chat_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - pg-chat-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chat"]
      interval: 5s
      timeout: 5s
      retries: 5

  message_service_db:
    image: postgres:15-alpine
    container_name: message_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message
    ports:
      - "5434:5432"
    networks:
      - app-network
    volumes:
      - pg-message-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d message"]
      interval: 5s
      timeout: 5s
      retries: 5

  fcm_service_db:
    image: postgres:15-alpine
    container_name: fcm_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fcm
    ports:
      - "5435:5432"
    networks:
      - app-network
    volumes:
      - pg-fcm-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fcm"]
      interval: 5s
      timeout: 5s
      retries: 5


#####SERVICES#####

  redis-service:
    image: redis:alpine3.22
    container_name: redis-service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data

  service-registry:
    image: joelgallan/service-registry:latest
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/ || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5

  auth-service:
    image: joelgallan/auth-service:latest
    container_name: auth-service
    restart: always
    ports:
      - "8088:8088"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      redis-service:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  api-gateway:
    image: joelgallan/api-gateway:latest
    container_name: api-gateway
    restart: always
    depends_on:
      redis-service:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - app-network
    env_file:
      - .env


  user-service:
    image: joelgallan/user-service:latest
    container_name: user-service
    restart: always
    depends_on:
      redis-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

#  websocket-service:
#    image: joelgallan/websocket-service:latest
#    container_name: websocket-service
#    restart: always
#    depends_on:
#      redis-service:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    ports:
#      - "8082:8082"
#    networks:
#      - app-network
#    env_file:
#      - .env

  message-service:
    image: joelgallan/message-service:latest
    container_name: message-service
    restart: always
    depends_on:
      redis-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8085:8085"
    networks:
      - app-network
    env_file:
      - .env

  chat-service:
    image: joelgallan/chat-service:latest
    container_name: chat-service
    restart: always
    depends_on:
      redis-service:
        condition: service_healthy
    ports:
      - "8084:8084"
    networks:
      - app-network
    env_file:
      - .env

  fcm-service:
    image: joelgallan/fcm-service:latest
    container_name: fcm-service
    restart: always
    depends_on:
      redis-service:
        condition: service_healthy
    ports:
      - "8089:8089"
    networks:
      - app-network
    env_file:
      - .env

  mqtt-service:
    image: joelgallan/mqtt-service:latest
    container_name: mqtt-service
    restart: always
    entrypoint: [ "/wait-for-emqx.sh", "emqx-service", "your-original-cmd" ]
    depends_on:
      redis-service:
        condition: service_healthy
      emqx-service:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env


volumes:
  redis-data:
  pg-user-data:
  pg-chat-data:
  pg-message-data:
  pg-fcm-data:
  emqx-data:
  emqx-log:


