version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  service-registry:
    image: joelgallan/service-registry:latest
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    image: joelgallan/api-gateway:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8001:8001"

  user-service:
    image: joelgallan/user-service:latest
    container_name: user-service
    restart: always
    ports:
      - "8080:8080"

  auth-service:
    image: joelgallan/auth-service:latest
    container_name: auth-service   # fixed duplicate container_name
    restart: always
    ports:
      - "8082:8082"

