version: '3.8'

networks:
  app-network:
    driver: bridge

services:

  redis-service:
    image: redis:alpine3.22
    container_name: redis-service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  auth-service:
    image: joelgallan/auth-service:latest
    container_name: auth-service
    restart: always
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      # These environment variables override the defaults in application.properties
      - SPRING_DATA_REDIS_HOST=redis-service
    depends_on:
      redis-service:
        condition: service_healthy

  service-registry:
    image: joelgallan/service-registry:latest
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"
    networks:
      - app-network

  api-gateway:
    image: joelgallan/api-gateway:latest
    container_name: api-gateway
    restart: always
    depends_on:
      - service-registry
    ports:
      - "8001:8001"
    networks:
      - app-network

  user-service:
    image: joelgallan/user-service:latest
    container_name: user-service
    restart: always
    depends_on:
      - service-registry
    ports:
      - "8080:8080"
    networks:
      - app-network
#

