services:
#  db:
#    image: postgres:latest
#    container_name: chat-app
#    restart: always
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


volumes:
  pgdata: