spring.application.name=websocket-service
server.port=8082

spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true