spring.application.name=websocket-service
server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret


# STOMP relay configuration (for WebSocket STOMP relay)
stomp.relay.host=localhost
stomp.relay.port=61613
stomp.relay.username=myuser
stomp.relay.password=secret

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true