spring.application.name=websocket-service
server.port=8082

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true