server:
  port: 8001

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

            - id: websocket-service
              uri: lb:ws://websocket-service
              predicates:
                - Path=/ws/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

jwt:
  secret: ${JWT_SECRET}
  exp:
    time: ${JWT_EXP_TIME}
  issuer: ${JWT_ISSUER}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
