services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"     # MQTT TCP
      - "18083:18083"   # Dashboard
      - "8083:8083"     # MQTT WebSocket
    environment:
      EMQX_NODE__NAME: emqx@127.0.0.1
      EMQX_ALLOW_ANONYMOUS: "true"   # Optional for local testing
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "admin123" # Dashboard login
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/status"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  emqx-data:
    name: emqx-data
  emqx-log:
    name: emqx-log


  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mosquitto
  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"
  #   volumes:
  #     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     - ./mosquitto/data:/mosquitto/data
  #     - ./mosquitto/log:/mosquitto/log

