spring.application.name=fcm-service
server.port=8089

#postgres-db
spring.datasource.url=${FCM_SERVICE_DATASOURCE_URL}
spring.datasource.username=${FCM_SERVICE_DATASOURCE_USERNAME}
spring.datasource.password=${FCM_SERVICE_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=5000


eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}