spring.application.name=chat-service
server.port=8084

#postgres-db
spring.datasource.url=${CHAT_SERVICE_DATASOURCE_URL}
spring.datasource.username=${CHAT_SERVICE_DATASOURCE_USERNAME}
spring.datasource.password=${CHAT_SERVICE_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true