name: Build and Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'user-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image for API Gateway
      - name: Build Docker image
        run: docker build -t joelgallan/user-service:latest ./user-service

      # 4. Push Docker image
      - name: Push Docker image
        run: docker push joelgallan/user-service:latest

      # 5. Deploy user service on VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/apps/circle-app
            docker compose pull user-service
            docker compose up -d user-service
            docker image prune -f
